In [8]:
#array contains similar data types..                                         
#if we given list contains multiple data types elements, 
#it automatically converts all elements into higher data type

#In this example it converting int to string

import numpy as np
l=[1,2,3,4,'p']
nn=np.array(l) 
print(nn)
type(nn)

['1' '2' '3' '4' '200000000' 'p']


numpy.ndarray

In [17]:
#two -Dimensional array

l1=[1,2,3,4]
l2=[10,20,30,40]
a=np.array([l1,l2])
print(a)


[[ 3  4  5  6]
 [12 22 32 42]]


In [18]:
#arrays are designed to perform Vectorized operation on arrays
#will perform operations on all elements of array

#if size is fixed in arrays then we can't modify it , but in list it is possible

print(a+2)

[[ 3  4  5  6]
 [12 22 32 42]]


In [16]:
l=[1,2,3,4]   # not possible
l+2

TypeError: can only concatenate list (not "int") to list

In [24]:
#Restricting array to only contain one particular data types
#dtype --> is a attribute  (bool,int,float,str,object)

arr=np.array([90,89],dtype='int')
print(arr)

arr=np.array([90,89,'pp'],dtype='int')
print(arr)


[90 89]
[90 89 'pp']


ValueError: invalid literal for int() with base 10: 'pp'

In [26]:
##If you want to consider elements of diff datatypes in same array then set dtype as "object"

arr=np.array([90,89,'pp'],dtype='object')
print(arr)

[90 89 'pp']


In [27]:
import numpy as np
l=[[1,0,3],['4','5','6']]
a=np.array(l,dtype='bool')
a

array([[ True, False,  True],
       [ True,  True,  True]])

In [29]:
import numpy as np
l=[[1,0,3],['4','5','6']]
a=np.array(l,dtype='int')
a

array([[1, 0, 3],
       [4, 5, 6]])

In [30]:
#tolist  --> To convert an array into list
a.tolist()   

#numpy object occupies lesser space than a list in python

[[1, 0, 3], [4, 5, 6]]

In [32]:
#shape,types,dimensions of array

a.shape   #to know shape in terms of rows and columns

(2, 3)

In [34]:
a.dtype  #to know the type of the data stored in an array

dtype('int32')

In [35]:
a.size #to know the total number of elements

6

In [36]:
a.ndim   #to know which dimensional array it is

2