### Numpy Library
* Processing N-Dimensional arrays

In [10]:
import numpy as np

arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(arr[1][0])
print(arr[0][0])
print(arr)

10
1
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [13]:
arr=np.array((90,80,70)) #creating array from Tuple 
print(arr)

[90 80 70]


In [14]:
b=np.arange(15)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
n=np.random.randint(0,2,size=(3,3))
n


array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 1]])

In [19]:
x=np.random.randint(5, size=(2, 4))
x

array([[1, 2, 4, 0],
       [1, 0, 4, 2]])

In [22]:
x.ndim
x.size
x.shape
x.dtype
x.itemsize
x.nbytes

32

In [25]:
x.reshape([4,2])

array([[1, 2],
       [4, 0],
       [1, 0],
       [4, 2]])

In [26]:
x.itemsize

4

In [27]:
x.dtype

dtype('int32')

In [28]:
x.nbytes

32

In [29]:
import numpy as np
ma=np.ones((3,3))
print(ma)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
5
1 2 3 4 5

In [6]:
n=int(input())
li=[]
s=input().split()
for i in s:
    li.append(int(i))
    
def su(li):
    s=0
    for i in li:
        s=s+i
    print(s)

su(li)

6
1 2 3 4 5 6
21


In [4]:
[i*2 for i in range(1,10)]

[2, 4, 6, 8, 10, 12, 14, 16, 18]

## Pandas
### Use Cases

* Data Cleaning
* Data Transformation
* Data Analysis
* Notations

* Series
* DataFrames

In [7]:
import pandas as pd

internal1={'st1':100,'st2':200,'st3':300}

internal2={'st1':500,'st2':600,'st3':700}

p1=pd.Series(internal1)
p2=pd.Series(internal2)
print(p1)
print(p2)

st1    100
st2    200
st3    300
dtype: int64
st1    500
st2    600
st3    700
dtype: int64


In [8]:
final = {'Internal1':internal1, 'Internal2':internal2}

final = pd.DataFrame(final)
final['Internal1']

st1    100
st2    200
st3    300
Name: Internal1, dtype: int64

In [ ]:
n=int(input())


12->681

In [9]:
final

Internal1  Internal2
st1        100        500
st2        200        600
st3        300        700

In [12]:
final.columns  # Names of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [14]:
final.values   # Names of all rows

array([[100, 500],
       [200, 600],
       [300, 700]], dtype=int64)

In [15]:
final.values[2]

array([300, 700], dtype=int64)

In [18]:
final.values[2,0]=25
final.values[2][0]

25

In [25]:
for row in final.values:
    print('Internal1 - ',row[0],', Internal2 - ',row[1])

Internal1 -  100 , Internal2 -  500
Internal1 -  200 , Internal2 -  600
Internal1 -  25 , Internal2 -  700


In [26]:
final


Internal1  Internal2
st1        100        500
st2        200        600
st3         25        700

In [27]:

final.loc['s4'] = [20, 18]
final

Internal1  Internal2
st1        100        500
st2        200        600
st3         25        700
s4          20         18

In [66]:
final

Internal1  Internal2
st2        200        600
st3         12         25

In [68]:
final = final.drop('st2')
final

Internal1  Internal2
st3         12         25

In [34]:
final.values[2] = [12,25]
final

Internal1  Internal2
st1        100        500
st2        200        600
st3         12         25
s4          20         18

In [39]:
# Reading CSV file data
import pandas as pd
filepath = 'DataFiles/Income.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [40]:

# Extract income of all states in 2013

#California : 57528

for row in incomedf.values:
    print(row[1], ':', row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [41]:
# Average income of all states in year 2012

sum = 0
for row in incomedf.values:
    sum += row[-2]
    
sum/len(incomedf.values)

50038.8